# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:
    - autolink
    - strikethrough
highlighter:      pygments

baseurl:          ""
permalink:        pretty

# Setup
title:            perlun.eu.org
name:             perlun.eu.org
paginate:         10

category_archive:
  slugify:        true

exclude: [vendor]

languages: ["xx", "sv", "en"]
exclude_from_localizations: ["images", "public"]

gems:
  - jekyll-multiple-languages-plugin
  - jekyll-paginate
  - jemoji
